name: Build Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.ORG_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --no-cache --tag engraph-worker:$(date +%s)
